# Generated by Django 4.2 on 2025-10-21 10:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_conversationparticipant_unique_together_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversation',
            name='private_members',
            field=models.JSONField(blank=True, db_index=True, help_text='私聊时存放 [user_id1, user_id2]，升序', null=True),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='read_up_to_msg_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='greater_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='lesser_id',
            field=models.PositiveIntegerField(db_index=True, default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_recalled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='recall_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)]),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['greater_id', 'status'], name='chat_greater_status_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['lesser_id', 'status'], name='chat_lesser_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(('type', models.Value('group')), models.Q(('type', models.Value('private')), ('private_members__length', 2)), _connector='OR'), name='private_must_have_two_members'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('type', models.Value('private'))), fields=('private_members',), name='uniq_private_conv'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('user', 'conversation'), name='uniq_user_conv'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.CheckConstraint(check=models.Q(('lesser_id', models.F('greater_id')), _negated=True), name='chat_no_self_friend'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('lesser_id', 'greater_id'), name='chat_uniq_friend_pair'),
        ),
        migrations.AddConstraint(
            model_name='messageread',
            constraint=models.UniqueConstraint(fields=('user', 'message'), name='uniq_read'),
        ),
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='last_read',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
    ]
