# Generated by Django 4.2 on 2025-10-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversationparticipant_unique_together_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='friendrequest',
        #     name='chat_no_self_friend',
        # ),
        # migrations.RemoveIndex(
        #     model_name='friendrequest',
        #     name='chat_greater_status_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='friendrequest',
        #     name='chat_lesser_status_idx',
        # ),
        migrations.AddField(
            model_name='friendrequest',
            name='from_user_id',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='to_user_id',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['from_user_id', 'status'], name='chat_from_status_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['to_user_id', 'status'], name='chat_to_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.CheckConstraint(check=models.Q(('from_user_id', models.F('to_user_id')), _negated=True), name='chat_no_self_request'),
        ),
    ]
