# Generated by Django 4.2 on 2025-11-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_friendrequest_chat_no_self_friend_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='friendrequest',
        #     name='chat_no_self_friend',
        # ),
        # migrations.RemoveIndex(
        #     model_name='friendrequest',
        #     name='chat_greater_status_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='friendrequest',
        #     name='chat_lesser_status_idx',
        # ),
    ]
