# Generated by Django 4.2 on 2025-11-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_friendrequest_chat_no_self_friend_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='friendrequest',
        #     name='chat_no_self_friend',
        # ),
        # migrations.RemoveIndex(
        #     model_name='friendrequest',
        #     name='chat_greater_status_idx',
        # ),
        # migrations.RemoveIndex(
        #     model_name='friendrequest',
        #     name='chat_lesser_status_idx',
        # ),
        migrations.AddField(
            model_name='conversation',
            name='is_dissolved',
            field=models.BooleanField(default=False, verbose_name='已解散'),
        ),
    ]
