# Generated by Django 4.2.2 on 2025-04-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
