# Generated by Django 4.2.2 on 2025-04-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user_list",
        ),
    ]
