# Generated by Django 4.2.2 on 2025-04-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(default="", max_length=11, unique=True),
        ),
    ]
