# Generated by Django 4.2.2 on 2025-04-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_avatar_user_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(default="00000000000", max_length=11, unique=True),
        ),
    ]
