# Generated by Django 4.2.2 on 2025-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.IntegerField(default=1),
        ),
    ]
