# Generated by Django 4.2.2 on 2025-04-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_user_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="id",
            new_name="user_id",
        ),
    ]
