# Generated by Django 4.2.2 on 2025-04-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_rename_id_user_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("permission_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "permission_name",
                    models.CharField(default="未命名权限", max_length=20),
                ),
            ],
            options={
                "db_table": "permission",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(default="普通用户", max_length=20)),
                (
                    "permissions",
                    models.ManyToManyField(related_name="roles", to="user.permission"),
                ),
            ],
            options={
                "db_table": "role",
            },
        ),
    ]
