# Generated by Django 4.2.2 on 2025-04-26 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_permission_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="user.role",
            ),
        ),
    ]
