# Generated by Django 4.2.2 on 2025-04-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_role_created_at_role_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="role_desc",
            field=models.TextField(default=""),
        ),
    ]
