# Generated by Django 4.2.2 on 2025-04-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_role_role_desc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="permissions",
            new_name="permission",
        ),
    ]
