# Generated by Django 4.2.2 on 2025-04-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_rename_permissions_role_permission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="permission",
            new_name="permission_id",
        ),
    ]
