# Generated by Django 4.2.2 on 2025-04-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_rename_permission_role_permission_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="permission_id",
            new_name="permission",
        ),
    ]
