# Generated by Django 4.2.2 on 2025-04-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_rename_permission_id_role_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission2",
            fields=[
                ("permission2_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "permission2_name",
                    models.CharField(default="未命名权限", max_length=20),
                ),
            ],
            options={
                "db_table": "permission2",
            },
        ),
    ]
