# Generated by Django 4.2.2 on 2025-04-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_permission2"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="permission2",
            field=models.ManyToManyField(
                related_name="permission2", to="user.permission2"
            ),
        ),
    ]
