# Generated by Django 4.2.2 on 2025-04-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_permission_permission2"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaiDan",
            fields=[
                ("auth_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "icon",
                    models.CharField(blank=True, default="icon-home", max_length=200),
                ),
                ("auth_name", models.CharField(default="", max_length=20)),
                ("path", models.CharField(blank=True, default="", max_length=200)),
                ("type", models.IntegerField(default=1)),
                ("auth_pid", models.IntegerField(default=0)),
                (
                    "auth_pname",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("keep_alive", models.IntegerField(default=1)),
                ("component", models.CharField(blank=True, default="", max_length=200)),
                ("sort", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "CaiDan",
            },
        ),
        migrations.CreateModel(
            name="CaiDan2",
            fields=[
                ("auth_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "icon",
                    models.CharField(blank=True, default="icon-home", max_length=200),
                ),
                ("auth_name", models.CharField(default="", max_length=20)),
                ("path", models.CharField(blank=True, default="", max_length=200)),
                ("type", models.IntegerField(default=1)),
                ("auth_pid", models.IntegerField(default=1)),
                (
                    "auth_pname",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("keep_alive", models.IntegerField(default=1)),
                ("component", models.CharField(blank=True, default="", max_length=200)),
                ("sort", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "CaiDan2",
            },
        ),
    ]
