# Generated by Django 4.2.2 on 2025-04-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_caidan_caidan2"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="caidan",
            table="caidan",
        ),
        migrations.AlterModelTable(
            name="caidan2",
            table="caidan2",
        ),
    ]
