# Generated by Django 4.2.2 on 2025-04-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_alter_caidan_table_alter_caidan2_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caidan",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
