# Generated by Django 4.2.2 on 2025-04-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_alter_caidan_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="permission2",
            field=models.ManyToManyField(
                related_name="permissions", to="user.permission2"
            ),
        ),
    ]
