# Generated by Django 4.2.2 on 2025-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_alter_permission_permission2"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permission2",
            field=models.ManyToManyField(related_name="roles", to="user.permission2"),
        ),
    ]
