# Generated by Django 4.2.2 on 2025-04-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_role_permission2"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission2",
            name="caidan2",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="user.caidan2",
            ),
            preserve_default=False,
        ),
    ]
