# Generated by Django 4.2 on 2025-10-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_conversation_message_friendrequest_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messageread',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messageread',
            name='user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationParticipant',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageRead',
        ),
    ]
